### ISSUE TITLE
Investigate potential sponsors and sources of funding

### ISSUE THREAD

**Issue by NicholasRostant** [abercompsoc/meetings#35]
_Assigned to Jack Webb_

**Comment by jackwebb6** [comment]
Can't assign myself for some reason

User is @jackwebb6

**Comment by kragniz** [comment]
@jackwebb6 stupidly, only members of a github org can be assigned to issues

**Comment by kragniz** [comment]
I invited you, and you'll be able to be assigned once you accept the invitation

**Comment by sap218** [comment]
So sponsorships are now one of the jobs that can also be for the socials secs (pubs/etc).
- should look into Castle Hotel (owner/manager is a comp-sci alumnus) - @alt38 @Sanae45 
- Treasurer & President can communicate w/ BCS, department, Union, etc.
