### ISSUE TITLE
Investigate options for society stickers

### ISSUE THREAD

**Issue by NicholasRostant** [abercompsoc/meetings#36]
_Assigned to Jack Webb_

**Comment by jackwebb6** [comment]
Got a good SVG of the logo now, investigating suppliers now...

**Comment by Danyc0** [comment]
Birmingham CSS just got 500 stickers for £121 from Sticker Mule (https://www.stickermule.com/uk) and they're great quality (pretty much the same quality as 'the good ones from FOSDEM', but slightly worse than the Github stickers). They're about 85mm*55mm.
