### ISSUE TITLE
Speak to union about CSTF membership options

### ISSUE THREAD

**Issue by Tebazil12** [abercompsoc/meetings#48]
See if they can create a membership option on the union website for CSTF. Requirements:
- all cstf must be part of AberCompSoc too
- have the option for current compsoc members to at any time get cstf membership if they want
- cstf membership is paid for (see their minutes when available)

**Comment by jackwebb6** [comment]
On second thoughts (see #49), I'll just go down and see what's what.

**Comment by jackwebb6** [comment]
This was the form I was sent by Pandora from the union. Is this what we're after - I'm not sure it is, and I think she has misunderstood me. Someone advise?

https://umabersu.wufoo.com/forms/p1en6rd00hkxq4v/

**Comment by Tebazil12** [comment]
That is one way we could work it, but im not sure if it is the best way. Using that we could create a product called 'cstf membership' and allow only CompSoc members to buy it and only people that buy it are officially cstf members, but its not quite the same as a membership option appearing on our union webpage. 

Did they say there was no way of making another membership type?

**Comment by jackwebb6** [comment]
I asked but didn't get an answer to that question I'm afraid. You could email her and ask, but that's all I was told. @me on Slack if you want her email.
