### ISSUE TITLE
Update union website

### ISSUE THREAD

**Issue by jackwebb6** [abercompsoc/meetings#49]
- Updated committee
- Inclusion of CSTF information (when applicable)

https://www.abersu.co.uk/societies/AberCompSoc/

**Comment by Tebazil12** [comment]
I think @CloudCoppola told the union about the new positions?

**Comment by jackwebb6** [comment]
I'll pop down, confirm this and get some details of #48 then

**Comment by jackwebb6** [comment]
Closed in preparation for new committee.
