### ISSUE TITLE
Fix Blurry Twitter Branding

### ISSUE THREAD

**Issue by jackwebb6** [abercompsoc/meetings#63]
Common problem with Twitter pages, should be a straightforward fix. 

Seen it fixed before using this guide:   
https://design.tutsplus.com/articles/the-simple-secret-to-banishing-blurry-twitter-header-photos--cms-26967

**Comment by NicholasRostant** [comment]
@jackwebb6  Assign to me and I'll get it done tonight

**Comment by NicholasRostant** [comment]
Profile picture and header replaced with some print quality versions, this can be closed.
